<?php

namespace common\models;
use common\models\Categories;
use Yii;

/**
 * This is the model class for table "{{%news}}".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $text
 */
class News extends \yii\db\ActiveRecord
{
    public $category;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%news}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['title','text'], 'required'],
            [['title'], 'string', 'max' => 255],
            [['category'],'each', 'rule' => ['integer']],
        ];
    }
    public function afterSave($insert, $changedAttributes)
    {
        if ( ! empty($this->category)) {
            $this->unlinkAll('categories');
            foreach ($this->category as $cat) {
                $category = Categories::find()->where(['id' => $cat])->one();
                if ($category) {
                    $this->link('categories', $category);
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'text' => 'Text',
        ];
    }
    public function getCategories() {
        return $this->hasMany(Categories::className(), ['id' => 'category_id'])
                    ->viaTable('category_news', ['news_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\NewsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\NewsQuery(get_called_class());
    }
}
